### ISSUE TITLE
Perhaps introduce a flag (e.g. --pessimistic) that includes any *possible* deprecations

### ISSUE THREAD

**Issue by frankmichel** [vuejs/vue-migration-helper#7] opened 2016-09-21 13:12 UTC
I just ran the migration helper and none of my `v-for="(...` got flagged since I believe the migration helper is just looking for "index" or "key" etc. within the brackets.

However I think that anything should be matched. So as soon as the code contains v-for followed by an opening parenthese like so

`v-for="(` or `v-for='(`

it should throw a notice. Because every scenario is possible: 

`v-for="(month, day) in someObject"`

Or am I thinking wrong?

**Comment by posva** [comment] 2016-09-21 14:40
The problem is that it'll always show up, even for already migrated `v-for`

**Comment by frankmichel** [comment] 2016-09-21 14:56
@posva True, but I'd rather have a "note" / "reminder" than forgetting to migrate those v-fors altogether. 

I assume that the use case for this tool is for users that want to migrate from 1.x to 2.x and not validate existing migrations. If i re-validate a directory I assume I already know which v-for's I have migrated and which ones I haven't.

**Comment by chrisvfritz** [comment] 2016-09-21 17:22
This is a tough situation. There are many cases like this, where there's only so much we can tell about the "intention" of the code. In some cases, like with custom directives, I've chosen to err on the side of overmatching because in 2.0 a directive is very rarely the right option. If we did that for more frequently-used features though, there'd be so many false positives that it'd be difficult to tell when you're really done with a migration. With this strategy, we'd also be unable to tell the difference between the array syntax with index vs the object syntax without an index.

And anyway, this tool _is_ also meant to validate migrations. It should be run more than once, because while refactoring users may introduce new deprecations. There are also some deprecations that rely on other deprecations being fixed first, so you'll have to run the tool more than once for that as well.

**Comment by frankmichel** [comment] 2016-09-21 17:36
@chrisvfritz I understand. Maybe a `--verbose` flag (or similar) could be introduced to cover those cases as well. But that would probably result in much more work setting up rules and checks.

**Comment by chrisvfritz** [comment] 2016-09-21 21:48
Thanks! We might introduce a flag like that at some point, though I wouldn't work on it until after rules for Vuex and Vue-Router are written.

It's also important to note that this tool will never find 100% of deprecations, but more like 80%. An advantage of parsing files line-by-line against regex like this is we can scan _any_ type of Vue code, whether it's a SPA, Laravel app, or even a blog post about Vue. Writing rules is also quite fast. The downside is we don't have context beyond a single line (though that is probably fixable) and we can't do more advanced static analysis to catch potential compile and run-time errors.

In the end, I made a judgement call that something we can build quickly that gets users 80% of the way there will be better than a tool that might take months to develop, but could catch 95% of deprecations.

**Comment by probil** [comment] 2016-09-22 22:12
One more possible deprecation:
* Vue 1.X:
```
<span v-for="n in 5">{{ n }}</span>
// renders [0 1 2 3 4]
```
* Vue 2.X:
```
<span v-for="n in 5">{{ n }}</span>
// renders [1 2 3 4 5]
```

**Comment by chrisvfritz** [comment] 2016-09-25 17:42
@probil Thanks! It's not currently possible to catch that deprecation with the helper, but I just added a note about this in the migration guide.

**Comment by chrisvfritz** [comment] 2017-05-10 18:29
Closing this (at least for now), as it's very unlikely it will ever rank highly enough on my list of priorities.

**Closed by chrisvfritz** 2017-05-10 18:29 UTC
Labels: feature request
